sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install .
  - pip install fake-factory
  - pip install coveralls
script:
  coverage run --source=datatables setup.py test
after_success:
  coveralls
